jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build dex-tools with Gradle
      run: './gradlew "-DGITHUB_REF_NAME=${GITHUB_REF_NAME}" check distZip

        '
    - continue-on-error: true
      if: success()
      name: Archive dex tools
      uses: actions/upload-artifact@v3
      with:
        name: dex-tools
        path: dex-tools/build/distributions/dex-tools-*.zip
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
